/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author SDavidLedesma
 */
public class MenuPrincipal extends javax.swing.JPanel {

    Controlador app;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Controlador app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblProductoss = new javax.swing.JLabel();
        lblProvedores = new javax.swing.JLabel();
        lblProveedoress = new javax.swing.JLabel();
        lblDevoluciones = new javax.swing.JLabel();
        lblDevolucioness = new javax.swing.JLabel();
        lblCompra = new javax.swing.JLabel();
        lblComprass = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        lblCajas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblReportess = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 0));
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setText("¡Hola de nuevo!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/soporte.png"))); // NOI18N

        lblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tornillo.png"))); // NOI18N
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMouseClicked(evt);
            }
        });

        lblProductoss.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblProductoss.setText("Productos");
        lblProductoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductossMouseClicked(evt);
            }
        });

        lblProvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pies.png"))); // NOI18N
        lblProvedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProvedoresMouseClicked(evt);
            }
        });

        lblProveedoress.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblProveedoress.setText("Proveedores");
        lblProveedoress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProveedoressMouseClicked(evt);
            }
        });

        lblDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/enchufe-de-pared.png"))); // NOI18N
        lblDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDevolucionesMouseClicked(evt);
            }
        });

        lblDevolucioness.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblDevolucioness.setText("Devoluciones");
        lblDevolucioness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDevolucionessMouseClicked(evt);
            }
        });

        lblCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tuerca.png"))); // NOI18N
        lblCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCompraMouseClicked(evt);
            }
        });

        lblComprass.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblComprass.setText("Compras");
        lblComprass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComprassMouseClicked(evt);
            }
        });

        lblCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ruedecita.png"))); // NOI18N
        lblCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCajaMouseClicked(evt);
            }
        });

        lblCajas.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblCajas.setText("Caja/Ventas");
        lblCajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCajasMouseClicked(evt);
            }
        });

        lblReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bisagra.png"))); // NOI18N
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportesMouseClicked(evt);
            }
        });

        lblReportess.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblReportess.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblProductos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblProductoss))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblProvedores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblProveedoress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblDevoluciones)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCompra)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblComprass)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCaja)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCajas)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblReportes)
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblDevolucioness)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReportess)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProductos)
                                .addGap(18, 18, 18)
                                .addComponent(lblProductoss)
                                .addGap(18, 18, 18)
                                .addComponent(lblProvedores)
                                .addGap(18, 18, 18)
                                .addComponent(lblProveedoress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDevoluciones))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblCompra)
                        .addGap(18, 18, 18)
                        .addComponent(lblComprass)
                        .addGap(18, 18, 18)
                        .addComponent(lblCaja)
                        .addGap(18, 18, 18)
                        .addComponent(lblCajas)
                        .addGap(18, 18, 18)
                        .addComponent(lblReportes)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblDevolucioness))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblReportess)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductosMouseClicked

    private void lblProductossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductossMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductossMouseClicked

    private void lblProvedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProvedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProvedoresMouseClicked

    private void lblProveedoressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedoressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProveedoressMouseClicked

    private void lblDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDevolucionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDevolucionesMouseClicked

    private void lblDevolucionessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDevolucionessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDevolucionessMouseClicked

    private void lblCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCompraMouseClicked

    private void lblComprassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblComprassMouseClicked

    private void lblCajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCajasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCajasMouseClicked

    private void lblCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCajaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCajaMouseClicked

    private void lblReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReportesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblCajas;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblComprass;
    private javax.swing.JLabel lblDevoluciones;
    private javax.swing.JLabel lblDevolucioness;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProductoss;
    private javax.swing.JLabel lblProvedores;
    private javax.swing.JLabel lblProveedoress;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblReportess;
    // End of variables declaration//GEN-END:variables
}
